
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_DATABASE: arquiweb
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: examplepass
    depends_on:
      - mysql

#   db:
#    image: mysql
##    command:--default-authentication-plugin=mysql_native_passwordv
#    restart: always
#    environment:
#      - "MYSQL_ROOT_PASSWORD: password"
#    ports:
#      - "3306:3306"